/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HostRouteImport } from './routes/host'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Screen2RouteImport } from './routes/screen.2'
import { Route as Screen1RouteImport } from './routes/screen.1'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as AdminDesignerLessonIdRouteImport } from './routes/admin.designer.$lessonId'

const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Screen2Route = Screen2RouteImport.update({
  id: '/screen/2',
  path: '/screen/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Screen1Route = Screen1RouteImport.update({
  id: '/screen/1',
  path: '/screen/1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDesignerLessonIdRoute = AdminDesignerLessonIdRouteImport.update({
  id: '/designer/$lessonId',
  path: '/designer/$lessonId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/host': typeof HostRoute
  '/api/proxy': typeof ApiProxyRoute
  '/screen/1': typeof Screen1Route
  '/screen/2': typeof Screen2Route
  '/admin/designer/$lessonId': typeof AdminDesignerLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/host': typeof HostRoute
  '/api/proxy': typeof ApiProxyRoute
  '/screen/1': typeof Screen1Route
  '/screen/2': typeof Screen2Route
  '/admin/designer/$lessonId': typeof AdminDesignerLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/host': typeof HostRoute
  '/api/proxy': typeof ApiProxyRoute
  '/screen/1': typeof Screen1Route
  '/screen/2': typeof Screen2Route
  '/admin/designer/$lessonId': typeof AdminDesignerLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/host'
    | '/api/proxy'
    | '/screen/1'
    | '/screen/2'
    | '/admin/designer/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/host'
    | '/api/proxy'
    | '/screen/1'
    | '/screen/2'
    | '/admin/designer/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/host'
    | '/api/proxy'
    | '/screen/1'
    | '/screen/2'
    | '/admin/designer/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HostRoute: typeof HostRoute
  ApiProxyRoute: typeof ApiProxyRoute
  Screen1Route: typeof Screen1Route
  Screen2Route: typeof Screen2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen/2': {
      id: '/screen/2'
      path: '/screen/2'
      fullPath: '/screen/2'
      preLoaderRoute: typeof Screen2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen/1': {
      id: '/screen/1'
      path: '/screen/1'
      fullPath: '/screen/1'
      preLoaderRoute: typeof Screen1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/designer/$lessonId': {
      id: '/admin/designer/$lessonId'
      path: '/designer/$lessonId'
      fullPath: '/admin/designer/$lessonId'
      preLoaderRoute: typeof AdminDesignerLessonIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDesignerLessonIdRoute: typeof AdminDesignerLessonIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDesignerLessonIdRoute: AdminDesignerLessonIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HostRoute: HostRoute,
  ApiProxyRoute: ApiProxyRoute,
  Screen1Route: Screen1Route,
  Screen2Route: Screen2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
