/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HostRouteImport } from './routes/host'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Screen2RouteImport } from './routes/screen.2'
import { Route as Screen1RouteImport } from './routes/screen.1'

const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Screen2Route = Screen2RouteImport.update({
  id: '/screen/2',
  path: '/screen/2',
  getParentRoute: () => rootRouteImport,
} as any)
const Screen1Route = Screen1RouteImport.update({
  id: '/screen/1',
  path: '/screen/1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/screen/1': typeof Screen1Route
  '/screen/2': typeof Screen2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/screen/1': typeof Screen1Route
  '/screen/2': typeof Screen2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/screen/1': typeof Screen1Route
  '/screen/2': typeof Screen2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/host' | '/screen/1' | '/screen/2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/host' | '/screen/1' | '/screen/2'
  id: '__root__' | '/' | '/admin' | '/host' | '/screen/1' | '/screen/2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HostRoute: typeof HostRoute
  Screen1Route: typeof Screen1Route
  Screen2Route: typeof Screen2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen/2': {
      id: '/screen/2'
      path: '/screen/2'
      fullPath: '/screen/2'
      preLoaderRoute: typeof Screen2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen/1': {
      id: '/screen/1'
      path: '/screen/1'
      fullPath: '/screen/1'
      preLoaderRoute: typeof Screen1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HostRoute: HostRoute,
  Screen1Route: Screen1Route,
  Screen2Route: Screen2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
